name: Release

on:
  push:
    branches:
      - "master"

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - name: Get Hash version
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" 
    - name: Build
      run: |
        npm install
        npx webpack --mode=production
        zip -r figmaXtailwind_v-${{steps.package-version.outputs.current-version}}.${{steps.vars.outputs.sha_short}}.zip * 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.FT_TOKEN }}"
        automatic_release_tag: "v-${{steps.package-version.outputs.current-version}}.${{steps.vars.outputs.sha_short}}"
        title: "Release v-${{steps.package-version.outputs.current-version}}.${{steps.vars.outputs.sha_short}}"
        prerelease: false
        files: |
          figmaXtailwind_v-${{steps.package-version.outputs.current-version}}.${{steps.vars.outputs.sha_short}}.zip.zip
