name: Release

on:
  push:
    branches:
      - "master"

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack --mode=production
        zip -r figmaXtailwind.zip *
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.FT_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Release Build"
        prerelease: false
        files: |
          figmaXtailwind.zip
